// Generated by gencpp from file laser_segmentation/PointArray.msg
// DO NOT EDIT!


#ifndef LASER_SEGMENTATION_MESSAGE_POINTARRAY_H
#define LASER_SEGMENTATION_MESSAGE_POINTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace laser_segmentation
{
template <class ContainerAllocator>
struct PointArray_
{
  typedef PointArray_<ContainerAllocator> Type;

  PointArray_()
    : segment()  {
    }
  PointArray_(const ContainerAllocator& _alloc)
    : segment(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _segment_type;
  _segment_type segment;





  typedef boost::shared_ptr< ::laser_segmentation::PointArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_segmentation::PointArray_<ContainerAllocator> const> ConstPtr;

}; // struct PointArray_

typedef ::laser_segmentation::PointArray_<std::allocator<void> > PointArray;

typedef boost::shared_ptr< ::laser_segmentation::PointArray > PointArrayPtr;
typedef boost::shared_ptr< ::laser_segmentation::PointArray const> PointArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_segmentation::PointArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_segmentation::PointArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_segmentation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'laser_segmentation': ['/home/pfeix/robot_host_ws/src/laser_segmentation/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_segmentation::PointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_segmentation::PointArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_segmentation::PointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_segmentation::PointArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_segmentation::PointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_segmentation::PointArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_segmentation::PointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8bab734a77cb06ef109b6411db4ce564";
  }

  static const char* value(const ::laser_segmentation::PointArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8bab734a77cb06efULL;
  static const uint64_t static_value2 = 0x109b6411db4ce564ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_segmentation::PointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_segmentation/PointArray";
  }

  static const char* value(const ::laser_segmentation::PointArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_segmentation::PointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point32[]     segment\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::laser_segmentation::PointArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_segmentation::PointArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.segment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_segmentation::PointArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_segmentation::PointArray_<ContainerAllocator>& v)
  {
    s << indent << "segment[]" << std::endl;
    for (size_t i = 0; i < v.segment.size(); ++i)
    {
      s << indent << "  segment[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.segment[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SEGMENTATION_MESSAGE_POINTARRAY_H
