// Generated by gencpp from file laser_segmentation/PointCloudSegmented.msg
// DO NOT EDIT!


#ifndef LASER_SEGMENTATION_MESSAGE_POINTCLOUDSEGMENTED_H
#define LASER_SEGMENTATION_MESSAGE_POINTCLOUDSEGMENTED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <laser_segmentation/Segment.h>

namespace laser_segmentation
{
template <class ContainerAllocator>
struct PointCloudSegmented_
{
  typedef PointCloudSegmented_<ContainerAllocator> Type;

  PointCloudSegmented_()
    : header()
    , segments()  {
    }
  PointCloudSegmented_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , segments(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::laser_segmentation::Segment_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::laser_segmentation::Segment_<ContainerAllocator> >::other >  _segments_type;
  _segments_type segments;





  typedef boost::shared_ptr< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloudSegmented_

typedef ::laser_segmentation::PointCloudSegmented_<std::allocator<void> > PointCloudSegmented;

typedef boost::shared_ptr< ::laser_segmentation::PointCloudSegmented > PointCloudSegmentedPtr;
typedef boost::shared_ptr< ::laser_segmentation::PointCloudSegmented const> PointCloudSegmentedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_segmentation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'laser_segmentation': ['/home/pfeix/robot_host_ws/src/laser_segmentation/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01f27048a4424acfc2e3c1dd6636c9d4";
  }

  static const char* value(const ::laser_segmentation::PointCloudSegmented_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01f27048a4424acfULL;
  static const uint64_t static_value2 = 0xc2e3c1dd6636c9d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_segmentation/PointCloudSegmented";
  }

  static const char* value(const ::laser_segmentation::PointCloudSegmented_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
laser_segmentation/Segment[] segments\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: laser_segmentation/Segment\n\
geometry_msgs/Point32[] segment\n\
int32 class_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::laser_segmentation::PointCloudSegmented_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.segments);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloudSegmented_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_segmentation::PointCloudSegmented_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_segmentation::PointCloudSegmented_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "segments[]" << std::endl;
    for (size_t i = 0; i < v.segments.size(); ++i)
    {
      s << indent << "  segments[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::laser_segmentation::Segment_<ContainerAllocator> >::stream(s, indent + "    ", v.segments[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SEGMENTATION_MESSAGE_POINTCLOUDSEGMENTED_H
